kv_namespaces = [
  { binding = "SESSION", id = "3035a50c751a4aca9ad0c9a5d077d17b" }
]
compatibility_date = "2026-02-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[observability]
enabled = true

  [observability.logs]
  invocation_logs = true
  head_sampling_rate = 1
